language: node_js
node_js:
 - "8.2.1"

install:
 - npm install newman

before_script:
 - node --version
 - npm --version
 - node_modules/.bin/newman --version

script:
 - node_modules/.bin/newman run tests/yugioh_collection.postman_collection.json -e yugioh_env.postman_environment.json
